
---
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    # TODO: replace `<cluster-name>` with the right cluster name. E.g.
    #
    # cluster: test-cluster
    cluster: standalone

# Load and evaluate rules in these files every 'evaluation_interval' seconds.
# rule_files:

scrape_configs:
  - job_name: "broker"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
      - targets:
          - 'pulsar:8080'

  - job_name: "bookie"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
      - targets:
          - 'pulsar:8080'

  - job_name: "zookeeper"
    honor_labels: true
    static_configs:
      - targets:
          - 'pulsar:8080'