version: '3.9'

services:

  pulsar:
    container_name: pulsar
    hostname: pulsar
    image: streamnative/sn-pulsar:2.9.3.4
    command: >
      bash -c "bin/apply-config-from-env.py conf/standalone.conf &&
      exec bin/pulsar standalone -nss -nfw" # disable stream storage and functions worker
    environment:
      allowAutoTopicCreationType: partitioned
      brokerDeleteInactiveTopicsEnabled: "false"
      PULSAR_PREFIX_webServicePort: 8090
    ports:
      - 6650:6650
      - 8090:8090

networks:
  default:
    name: error-handling-patterns