version: '3.9'

services:

  prometheus:
    restart: always
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    volumes:
      - ../monitoring/prometheus/config.yml:/etc/prometheus/prometheus.yml
     # - ./monitoring/prometheus/config.yml:/etc
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://prometheus:9090"]
      interval: 2s
      timeout: 5s
      retries: 15

  grafana:
    image: streamnative/apache-pulsar-grafana-dashboard:latest
    environment:
      PULSAR_CLUSTER: standalone
      PULSAR_PROMETHEUS_URL: http://prometheus:9090
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    healthcheck:
      test: [ "CMD", "wget", "--tries=1", "--spider", "http://localhost:3000/api/health" ]
      interval: 2s
      timeout: 5s
      retries: 15

networks:
  default:
    name: error-handling-patterns
    external: true